// This file was generated by update.sh!

fn main() {
    cc::Build::new()
        .warnings(false)
        .extra_warnings(false)
        .static_flag(true)
        .include("./c")
        .file("c/AEAD_Poly1305_64.c")
        .file("c/FStar.c")
        .file("c/Hacl_Chacha20.c")
        .file("c/Hacl_Chacha20Poly1305.c")
        .file("c/Hacl_Chacha20_Vec128.c")
        .file("c/Hacl_Curve25519.c")
        .file("c/Hacl_Ed25519.c")
        .file("c/Hacl_HMAC_SHA2_256.c")
        .file("c/Hacl_Policies.c")
        .file("c/Hacl_Poly1305_32.c")
        .file("c/Hacl_Poly1305_64.c")
        .file("c/Hacl_SHA2_256.c")
        .file("c/Hacl_SHA2_384.c")
        .file("c/Hacl_SHA2_512.c")
        .file("c/Hacl_Salsa20.c")
        .file("c/Hacl_Unverified_Random.c")
        .file("c/NaCl.c")
        .file("c/haclnacl.c")
        .file("c/kremlib.c")
        .compile("chaclstar");
}
