#! /usr/bin/env nix-shell
#! nix-shell --pure -i sh -p rust-bindgen rustfmt git

set -e

if test -d hacl_git
then
  cd hacl_git
  git pull
  cd ..
else
  git clone --depth 50 https://github.com/project-everest/hacl-star hacl_git
fi

rm ./c/*
cp ./hacl_git/snapshots/hacl-c/* c/
git add ./c/*

cat <<EOF > build.rs
// This file was generated by update.sh!

fn main() {
    cc::Build::new()
        .warnings(false)
        .extra_warnings(false)
        .static_flag(true)
        .include("./c")
EOF

for f in c/*.c
do
  echo "        .file(\"$f\")" >> build.rs
done

cat <<EOF >> build.rs
        .compile("chaclstar");
}
EOF

bindgen ./c/haclnacl.h --whitelist-function "crypto_.*" --whitelist-var  "crypto_.*" > src/nacl.rs
bindgen ./c/Hacl_SHA2_256.h --whitelist-function "Hacl_.*" --whitelist-var  "Hacl_.*" > src/sha2_256.rs
bindgen ./c/Hacl_HMAC_SHA2_256.h --whitelist-function "Hacl_.*" --whitelist-var  "Hacl_.*" > src/hmac_sha2_256.rs
rustfmt src/nacl.rs