/* automatically generated by rust-bindgen */

pub const crypto_auth_PRIMITIVE: &'static [u8; 14usize] = b"hmacsha512256\0";
pub const crypto_auth_hmacsha512256_tweet_BYTES: u32 = 32;
pub const crypto_auth_hmacsha512256_tweet_KEYBYTES: u32 = 32;
pub const crypto_auth_hmacsha512256_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_auth_hmacsha512256_BYTES: u32 = 32;
pub const crypto_auth_hmacsha512256_KEYBYTES: u32 = 32;
pub const crypto_auth_hmacsha512256_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_auth_hmacsha512256_IMPLEMENTATION: &'static [u8; 32usize] =
    b"crypto_auth/hmacsha512256/tweet\0";
pub const crypto_box_PRIMITIVE: &'static [u8; 27usize] = b"curve25519xsalsa20poly1305\0";
pub const crypto_box_curve25519xsalsa20poly1305_tweet_PUBLICKEYBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_tweet_SECRETKEYBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_tweet_BEFORENMBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_tweet_NONCEBYTES: u32 = 24;
pub const crypto_box_curve25519xsalsa20poly1305_tweet_ZEROBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_tweet_BOXZEROBYTES: u32 = 16;
pub const crypto_box_curve25519xsalsa20poly1305_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_SECRETKEYBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_BEFORENMBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_NONCEBYTES: u32 = 24;
pub const crypto_box_curve25519xsalsa20poly1305_ZEROBYTES: u32 = 32;
pub const crypto_box_curve25519xsalsa20poly1305_BOXZEROBYTES: u32 = 16;
pub const crypto_box_curve25519xsalsa20poly1305_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_box_curve25519xsalsa20poly1305_IMPLEMENTATION: &'static [u8; 44usize] =
    b"crypto_box/curve25519xsalsa20poly1305/tweet\0";
pub const crypto_core_PRIMITIVE: &'static [u8; 8usize] = b"salsa20\0";
pub const crypto_core_salsa20_tweet_OUTPUTBYTES: u32 = 64;
pub const crypto_core_salsa20_tweet_INPUTBYTES: u32 = 16;
pub const crypto_core_salsa20_tweet_KEYBYTES: u32 = 32;
pub const crypto_core_salsa20_tweet_CONSTBYTES: u32 = 16;
pub const crypto_core_salsa20_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_core_salsa20_OUTPUTBYTES: u32 = 64;
pub const crypto_core_salsa20_INPUTBYTES: u32 = 16;
pub const crypto_core_salsa20_KEYBYTES: u32 = 32;
pub const crypto_core_salsa20_CONSTBYTES: u32 = 16;
pub const crypto_core_salsa20_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_core_salsa20_IMPLEMENTATION: &'static [u8; 26usize] =
    b"crypto_core/salsa20/tweet\0";
pub const crypto_core_hsalsa20_tweet_OUTPUTBYTES: u32 = 32;
pub const crypto_core_hsalsa20_tweet_INPUTBYTES: u32 = 16;
pub const crypto_core_hsalsa20_tweet_KEYBYTES: u32 = 32;
pub const crypto_core_hsalsa20_tweet_CONSTBYTES: u32 = 16;
pub const crypto_core_hsalsa20_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_core_hsalsa20_OUTPUTBYTES: u32 = 32;
pub const crypto_core_hsalsa20_INPUTBYTES: u32 = 16;
pub const crypto_core_hsalsa20_KEYBYTES: u32 = 32;
pub const crypto_core_hsalsa20_CONSTBYTES: u32 = 16;
pub const crypto_core_hsalsa20_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_core_hsalsa20_IMPLEMENTATION: &'static [u8; 27usize] =
    b"crypto_core/hsalsa20/tweet\0";
pub const crypto_hashblocks_PRIMITIVE: &'static [u8; 7usize] = b"sha512\0";
pub const crypto_hashblocks_sha512_tweet_STATEBYTES: u32 = 64;
pub const crypto_hashblocks_sha512_tweet_BLOCKBYTES: u32 = 128;
pub const crypto_hashblocks_sha512_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hashblocks_sha512_STATEBYTES: u32 = 64;
pub const crypto_hashblocks_sha512_BLOCKBYTES: u32 = 128;
pub const crypto_hashblocks_sha512_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hashblocks_sha512_IMPLEMENTATION: &'static [u8; 31usize] =
    b"crypto_hashblocks/sha512/tweet\0";
pub const crypto_hashblocks_sha256_tweet_STATEBYTES: u32 = 32;
pub const crypto_hashblocks_sha256_tweet_BLOCKBYTES: u32 = 64;
pub const crypto_hashblocks_sha256_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hashblocks_sha256_STATEBYTES: u32 = 32;
pub const crypto_hashblocks_sha256_BLOCKBYTES: u32 = 64;
pub const crypto_hashblocks_sha256_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hashblocks_sha256_IMPLEMENTATION: &'static [u8; 31usize] =
    b"crypto_hashblocks/sha256/tweet\0";
pub const crypto_hash_PRIMITIVE: &'static [u8; 7usize] = b"sha512\0";
pub const crypto_hash_sha512_tweet_BYTES: u32 = 64;
pub const crypto_hash_sha512_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hash_sha512_BYTES: u32 = 64;
pub const crypto_hash_sha512_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hash_sha512_IMPLEMENTATION: &'static [u8; 25usize] = b"crypto_hash/sha512/tweet\0";
pub const crypto_hash_sha256_tweet_BYTES: u32 = 32;
pub const crypto_hash_sha256_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hash_sha256_BYTES: u32 = 32;
pub const crypto_hash_sha256_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_hash_sha256_IMPLEMENTATION: &'static [u8; 25usize] = b"crypto_hash/sha256/tweet\0";
pub const crypto_onetimeauth_PRIMITIVE: &'static [u8; 9usize] = b"poly1305\0";
pub const crypto_onetimeauth_poly1305_tweet_BYTES: u32 = 16;
pub const crypto_onetimeauth_poly1305_tweet_KEYBYTES: u32 = 32;
pub const crypto_onetimeauth_poly1305_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_onetimeauth_poly1305_BYTES: u32 = 16;
pub const crypto_onetimeauth_poly1305_KEYBYTES: u32 = 32;
pub const crypto_onetimeauth_poly1305_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_onetimeauth_poly1305_IMPLEMENTATION: &'static [u8; 34usize] =
    b"crypto_onetimeauth/poly1305/tweet\0";
pub const crypto_scalarmult_PRIMITIVE: &'static [u8; 11usize] = b"curve25519\0";
pub const crypto_scalarmult_curve25519_tweet_BYTES: u32 = 32;
pub const crypto_scalarmult_curve25519_tweet_SCALARBYTES: u32 = 32;
pub const crypto_scalarmult_curve25519_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_scalarmult_curve25519_BYTES: u32 = 32;
pub const crypto_scalarmult_curve25519_SCALARBYTES: u32 = 32;
pub const crypto_scalarmult_curve25519_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_scalarmult_curve25519_IMPLEMENTATION: &'static [u8; 35usize] =
    b"crypto_scalarmult/curve25519/tweet\0";
pub const crypto_secretbox_PRIMITIVE: &'static [u8; 17usize] = b"xsalsa20poly1305\0";
pub const crypto_secretbox_xsalsa20poly1305_tweet_KEYBYTES: u32 = 32;
pub const crypto_secretbox_xsalsa20poly1305_tweet_NONCEBYTES: u32 = 24;
pub const crypto_secretbox_xsalsa20poly1305_tweet_ZEROBYTES: u32 = 32;
pub const crypto_secretbox_xsalsa20poly1305_tweet_BOXZEROBYTES: u32 = 16;
pub const crypto_secretbox_xsalsa20poly1305_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_secretbox_xsalsa20poly1305_KEYBYTES: u32 = 32;
pub const crypto_secretbox_xsalsa20poly1305_NONCEBYTES: u32 = 24;
pub const crypto_secretbox_xsalsa20poly1305_ZEROBYTES: u32 = 32;
pub const crypto_secretbox_xsalsa20poly1305_BOXZEROBYTES: u32 = 16;
pub const crypto_secretbox_xsalsa20poly1305_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_secretbox_xsalsa20poly1305_IMPLEMENTATION: &'static [u8; 40usize] =
    b"crypto_secretbox/xsalsa20poly1305/tweet\0";
pub const crypto_sign_PRIMITIVE: &'static [u8; 8usize] = b"ed25519\0";
pub const crypto_sign_ed25519_tweet_BYTES: u32 = 64;
pub const crypto_sign_ed25519_tweet_PUBLICKEYBYTES: u32 = 32;
pub const crypto_sign_ed25519_tweet_SECRETKEYBYTES: u32 = 64;
pub const crypto_sign_ed25519_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_sign_ed25519_BYTES: u32 = 64;
pub const crypto_sign_ed25519_PUBLICKEYBYTES: u32 = 32;
pub const crypto_sign_ed25519_SECRETKEYBYTES: u32 = 64;
pub const crypto_sign_ed25519_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_sign_ed25519_IMPLEMENTATION: &'static [u8; 26usize] =
    b"crypto_sign/ed25519/tweet\0";
pub const crypto_stream_PRIMITIVE: &'static [u8; 9usize] = b"xsalsa20\0";
pub const crypto_stream_xsalsa20_tweet_KEYBYTES: u32 = 32;
pub const crypto_stream_xsalsa20_tweet_NONCEBYTES: u32 = 24;
pub const crypto_stream_xsalsa20_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_stream_xsalsa20_KEYBYTES: u32 = 32;
pub const crypto_stream_xsalsa20_NONCEBYTES: u32 = 24;
pub const crypto_stream_xsalsa20_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_stream_xsalsa20_IMPLEMENTATION: &'static [u8; 29usize] =
    b"crypto_stream/xsalsa20/tweet\0";
pub const crypto_stream_salsa20_tweet_KEYBYTES: u32 = 32;
pub const crypto_stream_salsa20_tweet_NONCEBYTES: u32 = 8;
pub const crypto_stream_salsa20_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_stream_salsa20_KEYBYTES: u32 = 32;
pub const crypto_stream_salsa20_NONCEBYTES: u32 = 8;
pub const crypto_stream_salsa20_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_stream_salsa20_IMPLEMENTATION: &'static [u8; 28usize] =
    b"crypto_stream/salsa20/tweet\0";
pub const crypto_verify_PRIMITIVE: &'static [u8; 3usize] = b"16\0";
pub const crypto_verify_16_tweet_BYTES: u32 = 16;
pub const crypto_verify_16_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_verify_16_BYTES: u32 = 16;
pub const crypto_verify_16_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_verify_16_IMPLEMENTATION: &'static [u8; 23usize] = b"crypto_verify/16/tweet\0";
pub const crypto_verify_32_tweet_BYTES: u32 = 32;
pub const crypto_verify_32_tweet_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_verify_32_BYTES: u32 = 32;
pub const crypto_verify_32_VERSION: &'static [u8; 2usize] = b"-\0";
pub const crypto_verify_32_IMPLEMENTATION: &'static [u8; 23usize] = b"crypto_verify/32/tweet\0";
extern "C" {
    pub fn crypto_auth_hmacsha512256_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_auth_hmacsha512256_tweet_verify(
        arg1: *const ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_box_curve25519xsalsa20poly1305_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
        arg6: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_box_curve25519xsalsa20poly1305_tweet_open(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
        arg6: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_box_curve25519xsalsa20poly1305_tweet_keypair(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_box_curve25519xsalsa20poly1305_tweet_beforenm(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_box_curve25519xsalsa20poly1305_tweet_afternm(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_box_curve25519xsalsa20poly1305_tweet_open_afternm(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_core_salsa20_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_core_hsalsa20_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_hashblocks_sha512_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_hashblocks_sha256_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_hash_sha512_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_hash_sha256_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_onetimeauth_poly1305_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_onetimeauth_poly1305_tweet_verify(
        arg1: *const ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_scalarmult_curve25519_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_scalarmult_curve25519_tweet_base(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_secretbox_xsalsa20poly1305_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_secretbox_xsalsa20poly1305_tweet_open(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_sign_ed25519_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *mut ::std::os::raw::c_ulonglong,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: ::std::os::raw::c_ulonglong,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_sign_ed25519_tweet_open(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *mut ::std::os::raw::c_ulonglong,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: ::std::os::raw::c_ulonglong,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_sign_ed25519_tweet_keypair(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_stream_xsalsa20_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: ::std::os::raw::c_ulonglong,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_stream_xsalsa20_tweet_xor(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_stream_salsa20_tweet(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: ::std::os::raw::c_ulonglong,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_stream_salsa20_tweet_xor(
        arg1: *mut ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_ulonglong,
        arg4: *const ::std::os::raw::c_uchar,
        arg5: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_verify_16_tweet(
        arg1: *const ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_verify_32_tweet(
        arg1: *const ::std::os::raw::c_uchar,
        arg2: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
